ci:
  autoupdate_schedule: "monthly" # Like dependabot
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_prs: false # Comment "pre-commit.ci autofix" on a PR to trigger

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-toml
      - id: check-json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
  - repo: https://github.com/google/yamlfmt
    rev: v0.12.1
    hooks:
      - id: yamlfmt
        types_or: [yaml]
        exclude: ".*/vcr_cassettes/.*\\.yaml"

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.4"
    hooks:
      - id: "codespell"
        exclude: ".codespellignore|tests/.*"
        additional_dependencies: ["tomli"]

  - repo: https://github.com/citation-file-format/cffconvert
    rev: "054bda51dbe278b3e86f27c890e3f3ac877d616c"
    hooks:
      - id: "validate-cff"
        args:
          - "--verbose"
