ci:
  autoupdate_schedule: "monthly"  # Like dependabot
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_prs: false  # Comment "pre-commit.ci autofix" on a PR to trigger

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: check-toml
    - id: check-json
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.6
  hooks:
    - id: ruff
      args: ["--fix", "--exit-non-zero-on-fix"]
    - id: ruff-format
