[tool.poetry]
name = "earthaccess"
version = "0.9.0"
repository = "https://github.com/nsidc/earthaccess"
documentation = "https://earthaccess.readthedocs.io"
description = "Client library for NASA Earthdata APIs"
authors = ["earthaccess contributors"]
maintainers = [
    "Luis Lopez <betolin@gmail.com>",
    "Joseph H. Kennedy <jhkennedy@alaska.edu>",
    "James Bourbeau <james@coiled.io>",
    "Matt Fisher <mfisher87@gmail.com>",
    "Chuck Daniels <chuck@developmentseed.org>"
]
license = "MIT"
readme = "README.md"
classifiers = [
    "Environment :: Console",
    "Framework :: IPython",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "License :: OSI Approved :: MIT License",
]

# NOTE: Minimum dependencies are tested with the packages defined in the
# `ci/environment-mindeps.yaml` conda environment. When updating minimum dependencies
# here, make sure to also update `ci/environment-mindeps.yaml`.
[tool.poetry.dependencies]
python = ">=3.9,<4.0"
python-cmr = ">=0.10.0"
pqdm = ">=0.1"
requests = ">=2.26"
s3fs = ">=2022.11"
fsspec = ">=2022.11"
tinynetrc = "^1.3.1"
multimethod = ">=1.8"
importlib-resources = ">=6.3.2"
typing_extensions = ">=4.10.0"

## Optional dependencies; can be opted-in with extra specifications below
## This is so verbose because Poetry requires it: https://python-poetry.org/docs/pyproject#extras
## If we switch to PEP621 specification, we can specify extras (called
## "optional" under PEP621) with versions in one line:
#https://peps.python.org/pep-0621/#example
kerchunk = { version = ">=0.1.2", optional = true }
# kerchunk requires numpy, but numpy >=1.26.0 is required for Python 3.12 support
numpy = [
  { version = ">=1.24.0", optional = true, python = "<3.12" },
  { version = ">=1.26.0", optional = true, python = ">=3.12" }
]
dask = { version = ">=2022.1.0", optional = true }

# Dev
bump-my-version = { version = ">=0.10.0", optional = true }
pre-commit = { version = ">=2.4", optional = true }
ruff = { version = ">=0.4.2", optional = true }

# Test
mypy = { version = ">=0.812", optional = true }
pytest = { version = ">=6.0", optional = true }
pytest-cov = { version = ">=2.8", optional = true }
pytest-watch = { version = ">=4.2", optional = true }
python-magic = { version = ">=0.4", optional = true }
responses = { version = ">=0.14", optional = true }
types-requests = { version = ">=0.1", optional = true }
types-setuptools = { version = ">=0.1", optional = true }
vcrpy = { version = ">=6.0.1", optional = true }

# Docs
jupyterlab = { version = ">=3", optional = true }
ipywidgets = { version = ">=7.7.0", optional = true }
widgetsnbextension = { version = ">=3.6.0", optional = true }
# Prevent install of 1.6.0 because the module mkdocs.tests
# is no longer exported, which causes mkdocs-jupyter to
# break with a ModuleNotFoundError.
mkdocs = { version = ">=1.2,!=1.6.0", optional = true }
mkdocs-material = { version = ">=7.1,<10.0", optional = true }
mkdocs-redirects = { version = ">=1.2.1", optional = true }
markdown-callouts = { version = ">=0.2.0", optional = true }
markdown-include = { version = ">=0.6", optional = true }
mkdocstrings = {extras = ["python"], version = ">=0.19.0", optional = true}
mkdocs-jupyter = { version = ">=0.19.0", optional = true }
pymdown-extensions = { version = ">=9.2", optional = true }
pygments = { version = ">=2.11.1", optional = true }
# for notebook integrations and documentation examples
xarray = { version = ">=2023.01", optional = true }
matplotlib = { version = ">=3.3", optional = true }
h5netcdf = { version = ">=0.11", optional = true }
pyproj = [
  { version = ">=3.5.0", python = "<3.12", optional = true },
  { version = ">=3.6.1", python = ">=3.12", optional = true },
]
# The following error occurs when building the docs, so we must explicitly
# include lxml-html-clean as a dev dependency until mkdocs-jupyter is updated:
#
#   ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
#   Install lxml[html_clean] or lxml_html_clean directly.
#
# See https://github.com/danielfrg/mkdocs-jupyter/issues/200
# See https://github.com/danielfrg/mkdocs-jupyter/issues/197
lxml-html-clean = {version = ">=0.1.1", optional = true}

[tool.poetry.extras]
kerchunk = ["kerchunk", "dask"]
dev = ["bump-my-version", "pre-commit", "ruff"]
test = ["mypy", "pytest", "pytest-cov", "pytest-watch", "python-magic", "responses", "types-requests", "types-setuptools", "vcrpy"]
docs = [
  "jupyterlab",
  "mkdocs",
  "mkdocs-material",
  "mkdocs-redirects",
  "markdown-callouts",
  "markdown-include",
  "mkdocstrings",
  "mkdocs-jupyter",
  "pymdown-extensions",
  "ipywidgets",
  "widetsnbextension",
  "xarray",
  "matplotlib",
  "h5netcdf",
  "pyproj",
]

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest]
filterwarnings = ["error::UserWarning"]

[tool.mypy]
mypy_path = ["earthaccess", "tests", "stubs"]
disallow_untyped_defs = true
# TODO: incrementally work towards strict mode (currently too many errors)
# strict = true
pretty = true  # Show additional context in error messages
enable_error_code = "redundant-self"

[[tool.mypy.overrides]]
module = [
  "tests.*",
]
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = [
  "fsspec.*",
  "dask.*",
  "kerchunk.*",
  "pqdm.*",
  "s3fs",
  "tinynetrc.*",  # TODO: generate stubs for tinynetrc and remove this line
  "vcr.unittest",  # TODO: generate stubs for vcr and remove this line
]
ignore_missing_imports = true

[tool.pyright]
include = ["earthaccess"]
stubPath = "./stubs"

[tool.ruff]
line-length = 88
src = ["earthaccess", "stubs", "tests"]

[tool.ruff.lint]
extend-select = ["I", "T20", "D"]
ignore = ["D1", "D205", "D401", "D417"]

[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.ruff.lint.isort]
combine-as-imports = true

[tool.bumpversion]
current_version = "0.9.0"
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search   = '^version = "{current_version}"$'
replace  = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search   = "^## Unreleased$"
replace  = "## [v{new_version}] {now:%Y-%m-%d}"

[[tool.bumpversion.files]]
filename = "CITATION.cff"
search   = 'version: "{current_version}"'
replace  = 'version: "{new_version}"'

[[tool.bumpversion.files]]
filename = "CITATION.cff"
search   = 'date-released: "\d{{4}}-\d{{2}}-\d{{2}}"'
replace  = 'date-released: "{now:%Y-%m-%d}"'

[tool.codespell]
skip = 'poetry.lock,*.ipynb,*.yml,*.yaml,./tests'
ignore-words = ".codespellignore"
