name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.8
  - python-cmr=0.9.0
  - pqdm=0.1
  - requests=2.26
  - s3fs=2022.11
  - fsspec=2022.11
  - tinynetrc=1.3.1
  - multimethod=1.8
  - python-dateutil=2.8.2
  # test dependencies
  - responses
  - pytest
  - pytest-cov
