name: Test

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - env:
          EDL_USERNAME: ${{ secrets.EDL_USERNAME }}
          EDL_PASSWORD: ${{ secrets.EDL_PASSWORD }}
        run: poetry run bash scripts/integration-test.sh
